name = "Joseki"
uuid = "b588beb9-536a-5a7d-a241-c127386fde06"
author = ["Alex Mellnik <a.r.mellnik@gmail.com>"]
version = "0.2.2"

[deps]
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Sockets = "6462fe0b-24de-5631-8697-dd941f90decc"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
HTTP = "0.8.0"
JSON = "0.20, 0.21"
julia = "1.0"
